<?php

namespace TeamBundle\Repository;
use TeamBundle\Entity\Team;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    private $em;

    public function get($id)
    {
        return $this->getEntityManager()->getRepository('TeamBundle:Team')->find($id);
    }

    public function all()
    {
        return $this->getEntityManager()->getRepository('TeamBundle:Team')->findAll();
    }

    public function remove($id)
    {
        $this->em = $this->getEntityManager();

        $team = $this->em->getRepository('TeamBundle:Team')->find($id);
        $this->em->remove($team);
        $this->em->flush();
    }

    public function add(Team $team)
    {
        $this->em = $this->getEntityManager();
        $this->em->persist($team);
        $this->em->flush();
    }

    public function update()
    {
        $this->em = $this->getEntityManager();
        $this->em->flush();
    }
}
