<?php

namespace MemberBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function all()
    {
        return $this->getEntityManager()->getRepository('MemberBundle:Role')->findAll();
    }
}
