<?php

namespace TaskBundle\Repository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    private $em;

    public function all()
    {
        return $this->getEntityManager()->getRepository('TaskBundle:Action')->findAll();
    }
}
