member:
    resource: "@MemberBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    prefix:   /

team:
    resource: "@TeamBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
