<?php

namespace ProjectBundle\Repository;
use ProjectBundle\Entity\Project;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    private $em;

    public function getById($id)
    {
        return $this->getEntityManager()->getRepository('ProjectBundle:Project')->find($id);
    }

    public function all()
    {
        return $this->getEntityManager()->getRepository('ProjectBundle:Project')->findAll();
    }

    public function remove($id)
    {
        $this->em = $this->getEntityManager();

        $project = $this->em->getRepository('ProjectBundle:Project')->find($id);
        $this->em->remove($project);
        $this->em->flush();
    }

    public function add(Project $project)
    {
        $this->em = $this->getEntityManager();

        $this->em->persist($project);
        $this->em->flush();
    }

    public function update()
    {
        $this->em = $this->getEntityManager();
        $this->em->flush();
    }

    public function getProjectDetails()
    {
        $this->em = $this->getEntityManager();
        $connection = $this->em->getConnection();

        $statement = $connection->prepare('select
                                                p.pk_project_id,
                                                p.project_name,
                                                pt.project_type_name,
                                                t.team_name,
                                                p.project_created_date
                                                from tm_projects as p inner join tm_teams as t on p.fk_team_id = t.pk_team_id
                                                inner join tm_project_types as pt on p.fk_project_type_id = pt.pk_project_type_id');

        $statement->execute();
        $result = $statement->fetchAll();

        return $result;
    }
}
