<?php

namespace ProjectBundle\Repository;

/**
 * ProjectTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function all()
    {
        return $this->getEntityManager()->getRepository('ProjectBundle:ProjectType')->findAll();
    }
}
